// Code generated by Kitex v0.5.2. DO NOT EDIT.

package textpredictor

import (
	server "github.com/cloudwego/kitex/server"
	re "github.com/ishumei/krpc/protocols/text/kitex_gen/shumei/strategy/re"
)

// NewInvoker creates a server.Invoker with the given handler and options.
func NewInvoker(handler re.TextPredictor, opts ...server.Option) server.Invoker {
	var options []server.Option

	options = append(options, opts...)

	s := server.NewInvoker(options...)
	if err := s.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	if err := s.Init(); err != nil {
		panic(err)
	}
	return s
}
