// Code generated by Kitex v0.5.2. DO NOT EDIT.
package textpredictor

import (
	server "github.com/cloudwego/kitex/server"
	re "github.com/ishumei/krpc/protocols/text/kitex_gen/shumei/strategy/re"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler re.TextPredictor, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}
