// Code generated by Kitex v0.5.2. DO NOT EDIT.

package textpredictor

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	re "github.com/ishumei/krpc/protocols/text/kitex_gen/shumei/strategy/re"
)

func serviceInfo() *kitex.ServiceInfo {
	return textPredictorServiceInfo
}

var textPredictorServiceInfo = NewServiceInfo()

func NewServiceInfo() *kitex.ServiceInfo {
	serviceName := "TextPredictor"
	handlerType := (*re.TextPredictor)(nil)
	methods := map[string]kitex.MethodInfo{
		"predict": kitex.NewMethodInfo(predictHandler, newTextPredictorPredictArgs, newTextPredictorPredictResult, false),
		"health":  kitex.NewMethodInfo(healthHandler, newTextPredictorHealthArgs, newTextPredictorHealthResult, false),
	}
	extra := map[string]interface{}{
		"PackageName": "re",
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.5.2",
		Extra:           extra,
	}
	return svcInfo
}

func predictHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*re.TextPredictorPredictArgs)
	realResult := result.(*re.TextPredictorPredictResult)
	success, err := handler.(re.TextPredictor).Predict(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newTextPredictorPredictArgs() interface{} {
	return re.NewTextPredictorPredictArgs()
}

func newTextPredictorPredictResult() interface{} {
	return re.NewTextPredictorPredictResult()
}

func healthHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {

	realResult := result.(*re.TextPredictorHealthResult)
	success, err := handler.(re.TextPredictor).Health(ctx)
	if err != nil {
		return err
	}
	realResult.Success = &success
	return nil
}
func newTextPredictorHealthArgs() interface{} {
	return re.NewTextPredictorHealthArgs()
}

func newTextPredictorHealthResult() interface{} {
	return re.NewTextPredictorHealthResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Predict(ctx context.Context, request *re.TextPredictRequest) (r *re.TextPredictResult_, err error) {
	var _args re.TextPredictorPredictArgs
	_args.Request = request
	var _result re.TextPredictorPredictResult
	if err = p.c.Call(ctx, "predict", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Health(ctx context.Context) (r bool, err error) {
	var _args re.TextPredictorHealthArgs
	var _result re.TextPredictorHealthResult
	if err = p.c.Call(ctx, "health", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
