// Code generated by Kitex v0.11.3. DO NOT EDIT.

package eventpredictor

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	re "github.com/ishumei/krpc/protocols/event/kitex_gen/shumei/strategy/re"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"predict": kitex.NewMethodInfo(
		predictHandler,
		newEventPredictorPredictArgs,
		newEventPredictorPredictResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"health": kitex.NewMethodInfo(
		healthHandler,
		newEventPredictorHealthArgs,
		newEventPredictorHealthResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	eventPredictorServiceInfo                = NewServiceInfo()
	eventPredictorServiceInfoForClient       = NewServiceInfoForClient()
	eventPredictorServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return eventPredictorServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return eventPredictorServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return eventPredictorServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "EventPredictor"
	handlerType := (*re.EventPredictor)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "re",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.11.3",
		Extra:           extra,
	}
	return svcInfo
}

func predictHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*re.EventPredictorPredictArgs)
	realResult := result.(*re.EventPredictorPredictResult)
	success, err := handler.(re.EventPredictor).Predict(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newEventPredictorPredictArgs() interface{} {
	return re.NewEventPredictorPredictArgs()
}

func newEventPredictorPredictResult() interface{} {
	return re.NewEventPredictorPredictResult()
}

func healthHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	_ = arg.(*re.EventPredictorHealthArgs)
	realResult := result.(*re.EventPredictorHealthResult)
	success, err := handler.(re.EventPredictor).Health(ctx)
	if err != nil {
		return err
	}
	realResult.Success = &success
	return nil
}
func newEventPredictorHealthArgs() interface{} {
	return re.NewEventPredictorHealthArgs()
}

func newEventPredictorHealthResult() interface{} {
	return re.NewEventPredictorHealthResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Predict(ctx context.Context, request *re.EventPredictRequest) (r *re.EventPredictResult_, err error) {
	var _args re.EventPredictorPredictArgs
	_args.Request = request
	var _result re.EventPredictorPredictResult
	if err = p.c.Call(ctx, "predict", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Health(ctx context.Context) (r bool, err error) {
	var _args re.EventPredictorHealthArgs
	var _result re.EventPredictorHealthResult
	if err = p.c.Call(ctx, "health", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
