// Code generated by Kitex v0.11.3. DO NOT EDIT.

package imagepredictor

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	re "github.com/day253/krpc/protocols/image/kitex_gen/shumei/strategy/re"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"predict": kitex.NewMethodInfo(
		predictHandler,
		newImagePredictorPredictArgs,
		newImagePredictorPredictResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"health": kitex.NewMethodInfo(
		healthHandler,
		newImagePredictorHealthArgs,
		newImagePredictorHealthResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	imagePredictorServiceInfo                = NewServiceInfo()
	imagePredictorServiceInfoForClient       = NewServiceInfoForClient()
	imagePredictorServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return imagePredictorServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return imagePredictorServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return imagePredictorServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "ImagePredictor"
	handlerType := (*re.ImagePredictor)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "re",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.11.3",
		Extra:           extra,
	}
	return svcInfo
}

func predictHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*re.ImagePredictorPredictArgs)
	realResult := result.(*re.ImagePredictorPredictResult)
	success, err := handler.(re.ImagePredictor).Predict(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newImagePredictorPredictArgs() interface{} {
	return re.NewImagePredictorPredictArgs()
}

func newImagePredictorPredictResult() interface{} {
	return re.NewImagePredictorPredictResult()
}

func healthHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	_ = arg.(*re.ImagePredictorHealthArgs)
	realResult := result.(*re.ImagePredictorHealthResult)
	success, err := handler.(re.ImagePredictor).Health(ctx)
	if err != nil {
		return err
	}
	realResult.Success = &success
	return nil
}
func newImagePredictorHealthArgs() interface{} {
	return re.NewImagePredictorHealthArgs()
}

func newImagePredictorHealthResult() interface{} {
	return re.NewImagePredictorHealthResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Predict(ctx context.Context, request *re.ImagePredictRequest) (r *re.ImagePredictResult_, err error) {
	var _args re.ImagePredictorPredictArgs
	_args.Request = request
	var _result re.ImagePredictorPredictResult
	if err = p.c.Call(ctx, "predict", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Health(ctx context.Context) (r bool, err error) {
	var _args re.ImagePredictorHealthArgs
	var _result re.ImagePredictorHealthResult
	if err = p.c.Call(ctx, "health", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
