// Code generated by Kitex v0.5.2. DO NOT EDIT.

package imagepredictor

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	re "github.com/ishumei/krpc/protocols/image/kitex_gen/shumei/strategy/re"
)

func serviceInfo() *kitex.ServiceInfo {
	return imagePredictorServiceInfo
}

var imagePredictorServiceInfo = NewServiceInfo()

func NewServiceInfo() *kitex.ServiceInfo {
	serviceName := "ImagePredictor"
	handlerType := (*re.ImagePredictor)(nil)
	methods := map[string]kitex.MethodInfo{
		"predict": kitex.NewMethodInfo(predictHandler, newImagePredictorPredictArgs, newImagePredictorPredictResult, false),
		"health":  kitex.NewMethodInfo(healthHandler, newImagePredictorHealthArgs, newImagePredictorHealthResult, false),
	}
	extra := map[string]interface{}{
		"PackageName": "re",
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.5.2",
		Extra:           extra,
	}
	return svcInfo
}

func predictHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*re.ImagePredictorPredictArgs)
	realResult := result.(*re.ImagePredictorPredictResult)
	success, err := handler.(re.ImagePredictor).Predict(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newImagePredictorPredictArgs() interface{} {
	return re.NewImagePredictorPredictArgs()
}

func newImagePredictorPredictResult() interface{} {
	return re.NewImagePredictorPredictResult()
}

func healthHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {

	realResult := result.(*re.ImagePredictorHealthResult)
	success, err := handler.(re.ImagePredictor).Health(ctx)
	if err != nil {
		return err
	}
	realResult.Success = &success
	return nil
}
func newImagePredictorHealthArgs() interface{} {
	return re.NewImagePredictorHealthArgs()
}

func newImagePredictorHealthResult() interface{} {
	return re.NewImagePredictorHealthResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Predict(ctx context.Context, request *re.ImagePredictRequest) (r *re.ImagePredictResult_, err error) {
	var _args re.ImagePredictorPredictArgs
	_args.Request = request
	var _result re.ImagePredictorPredictResult
	if err = p.c.Call(ctx, "predict", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Health(ctx context.Context) (r bool, err error) {
	var _args re.ImagePredictorHealthArgs
	var _result re.ImagePredictorHealthResult
	if err = p.c.Call(ctx, "health", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
