// Code generated by Kitex v0.5.2. DO NOT EDIT.

package audiopredictor

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	re "github.com/ishumei/krpc/protocols/audio/kitex_gen/shumei/strategy/re"
)

func serviceInfo() *kitex.ServiceInfo {
	return audioPredictorServiceInfo
}

var audioPredictorServiceInfo = NewServiceInfo()

func NewServiceInfo() *kitex.ServiceInfo {
	serviceName := "AudioPredictor"
	handlerType := (*re.AudioPredictor)(nil)
	methods := map[string]kitex.MethodInfo{
		"predict": kitex.NewMethodInfo(predictHandler, newAudioPredictorPredictArgs, newAudioPredictorPredictResult, false),
		"health":  kitex.NewMethodInfo(healthHandler, newAudioPredictorHealthArgs, newAudioPredictorHealthResult, false),
	}
	extra := map[string]interface{}{
		"PackageName": "re",
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.5.2",
		Extra:           extra,
	}
	return svcInfo
}

func predictHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*re.AudioPredictorPredictArgs)
	realResult := result.(*re.AudioPredictorPredictResult)
	success, err := handler.(re.AudioPredictor).Predict(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newAudioPredictorPredictArgs() interface{} {
	return re.NewAudioPredictorPredictArgs()
}

func newAudioPredictorPredictResult() interface{} {
	return re.NewAudioPredictorPredictResult()
}

func healthHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {

	realResult := result.(*re.AudioPredictorHealthResult)
	success, err := handler.(re.AudioPredictor).Health(ctx)
	if err != nil {
		return err
	}
	realResult.Success = &success
	return nil
}
func newAudioPredictorHealthArgs() interface{} {
	return re.NewAudioPredictorHealthArgs()
}

func newAudioPredictorHealthResult() interface{} {
	return re.NewAudioPredictorHealthResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Predict(ctx context.Context, request *re.AudioPredictRequest) (r *re.AudioPredictResult_, err error) {
	var _args re.AudioPredictorPredictArgs
	_args.Request = request
	var _result re.AudioPredictorPredictResult
	if err = p.c.Call(ctx, "predict", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Health(ctx context.Context) (r bool, err error) {
	var _args re.AudioPredictorHealthArgs
	var _result re.AudioPredictorHealthResult
	if err = p.c.Call(ctx, "health", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
