// Code generated by Kitex v0.11.3. DO NOT EDIT.
package predictor

import (
	server "github.com/cloudwego/kitex/server"
	service "github.com/day253/krpc/protocols/arbiter/kitex_gen/com/shumei/service"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler service.Predictor, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)
	options = append(options, server.WithCompatibleMiddlewareForUnary())

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}

func RegisterService(svr server.Server, handler service.Predictor, opts ...server.RegisterOption) error {
	return svr.RegisterService(serviceInfo(), handler, opts...)
}
